version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "Kiper"
      POSTGRES_USER: "KiperUser"
      POSTGRES_PASSWORD: "KiperPass"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"
